{'application':{'type':'Application',
          'name':'Minimal',
    'backgrounds': [
    {'type':'Background',
          'name':'bgMin',
          'title':'PopuLister (PupAIS)',
          'size':(597, 449),

         'components': [

{'type':'Image', 
    'name':'splash', 
    'position':(0, -1), 
    'size':(597, 449), 
    'backgroundColor':(0, 0, 128), 
#    'file':'../data/pngs/splash449px597.png',
    'file':'../data/pngs/wideeyes.png',
    'foregroundColor':(255, 255, 255), 
    'visible':False, 
    },

{'type':'TextArea', 
    'name':'OopsAlert', 
    'position':(418, 218), 
    'size':(159, 22), 
    'alignment':'right', 
    'border':'none', 
    'editable':False, 
    'font':{'style': 'bold', 'faceName': u'Monospace', 'size': 12}, 
    'foregroundColor':(255, 0, 0), 
    'text':'Spurious data!', 
    },

{'type':'StaticText', 
    'name':'bearingTag', 
    'position':(316, 140), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Bearing:', 
    },

{'type':'StaticLine', 
    'name':'StaticLine1', 
    'position':(172, 370), 
    'size':(406, 3), 
    'backgroundColor':(233, 230, 212), 
    'layout':'horizontal', 
    },

{'type':'StaticText', 
    'name':'pollTag', 
    'position':(318, 401), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Present poll:', 
    },

{'type':'Button', 
    'name':'updateButton', 
    'position':(210, 391), 
    'size':(81, 31), 
    'backgroundColor':(21, 217, 21), 
    'font':{'style': 'bold', 'faceName': u'Arial', 'size': 9}, 
    'foregroundColor':(255, 255, 255), 
    'label':'Update', 
    },

{'type':'Image', 
    'name':'Image1', 
    'position':(114, 29), 
    'size':(127, 31), 
    'backgroundColor':(233, 230, 212), 
    'file':'../data/pngs/53.gif', 
    },

{'type':'StaticText', 
    'name':'PopulistTxt', 
    'position':(11, 33), 
    'size':(-1, 17), 
    'backgroundColor':(233, 230, 212), 
    'font':{'style': 'bold', 'faceName': u'Arial Narrow', 'size': 10}, 
    'foregroundColor':(165, 42, 42), 
    'text':'Targets in range:', 
    },

{'type':'StaticText', 
    'name':'NMiles', 
    'position':(287, 141), 
    'size':(24, -1), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial', 'size': 8}, 
    'foregroundColor':(150, 150, 150), 
    'text':'NM', 
    },

{'type':'StaticText', 
    'name':'DegreesCopyCopy', 
    'position':(287, 274), 
    'size':(24, -1), 
    'backgroundColor':(233, 230, 212), 
    'foregroundColor':(150, 150, 150), 
    'text':'Deg', 
    },

{'type':'StaticText', 
    'name':'DegreesCopy', 
    'position':(287, 226), 
    'size':(24, -1), 
    'backgroundColor':(233, 230, 212), 
    'foregroundColor':(150, 150, 150), 
    'text':'Deg', 
    },

{'type':'StaticText', 
    'name':'Degrees', 
    'position':(287, 249), 
    'size':(24, -1), 
    'backgroundColor':(233, 230, 212), 
    'foregroundColor':(150, 150, 150), 
    'text':'Deg', 
    },

{'type':'StaticText', 
    'name':'Knop', 
    'position':(287, 201), 
    'size':(24, -1), 
    'backgroundColor':(233, 230, 212), 
    'foregroundColor':(150, 150, 150), 
    'text':'Kn', 
    },

{'type':'StaticText', 
    'name':'mmsiTag', 
    'position':(167, 66), 
    'size':(36, -1), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11}, 
    'text':'MMSI:', 
    },

{'type':'StaticText', 
    'name':'clckTag', 
    'position':(426, 140), 
    'size':(58, -1), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Update:', 
    },

{'type':'StaticText', 
    'name':'HDGTag', 
    'position':(173, 275), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'HDG:', 
    },

{'type':'StaticText', 
    'name':'ROTTag', 
    'position':(175, 250), 
    'size':(29, -1), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'ROT:', 
    },

{'type':'StaticText', 
    'name':'COGTag', 
    'position':(171, 225), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'COG:', 
    },

{'type':'TextField', 
    'name':'ROT', 
    'position':(210, 245), 
    'size':(75, 24), 
    'alignment':'right', 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'HDG', 
    'position':(210, 270), 
    'size':(75, 24), 
    'alignment':'right', 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'COG', 
    'position':(210, 220), 
    'size':(75, 24), 
    'alignment':'right', 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'SOG', 
    'position':(210, 195), 
    'size':(75, 24), 
    'alignment':'right', 
    'editable':False, 
    },

{'type':'StaticText', 
    'name':'destTag', 
    'position':(370, 165), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Destin:', 
    },

{'type':'StaticText', 
    'name':'LONTag', 
    'position':(395, 275), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'LON:', 
    },

{'type':'StaticText', 
    'name':'LATTag', 
    'position':(395, 250), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'LAT:', 
    },

{'type':'StaticText', 
    'name':'navsTag', 
    'position':(387, 90), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'NS:', 
    },

{'type':'StaticText', 
    'name':'typeTag', 
    'position':(375, 65), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Type:', 
    },

{'type':'StaticText', 
    'name':'SOGTag', 
    'position':(172, 200), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'SOG:', 
    },

{'type':'StaticText', 
    'name':'LOATag', 
    'position':(371, 190), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'LOA:', 
    },

{'type':'StaticText', 
    'name':'beamTag', 
    'position':(486, 190), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Beam:', 
    },

{'type':'StaticText', 
    'name':'rangeTag', 
    'position':(161, 140), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Range:', 
    },

{'type':'StaticText', 
    'name':'callsTag', 
    'position':(155, 115), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Callsign:', 
    },

{'type':'StaticText', 
    'name':'nameTag', 
    'position':(165, 90), 
    'backgroundColor':(233, 230, 212), 
    'font':{'faceName': u'Arial Narrow', 'size': 11},
    'text':'Name:', 
    },

{'type':'TextField', 
    'name':'mmsi', 
    'position':(210, 60), 
    'size':(103, 24), 
    'backgroundColor':(245, 242, 223), 
    'editable':False, 
    'font':{'faceName': u'Courier 10 Pitch', 'size': 10}, 
    },

{'type':'TextField', 
    'name':'name', 
    'position':(210, 85), 
    'size':(172, 24), 
    'alignment':'center', 
    'backgroundColor':(255, 211, 89), 
    'editable':False, 
    'font':{'faceName': u'VL Gothic', 'size': 12}, 
    'foregroundColor':(255, 255, 255), 
    'text':'Namn', 
    },

{'type':'TextField', 
    'name':'vtype', 
    'position':(410, 60), 
    'size':(172, 24), 
    'backgroundColor':(233, 230, 212), 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'navs', 
    'position':(410, 85), 
    'size':(172, 24), 
    'backgroundColor':(233, 230, 212), 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'phono', 
    'position':(210, 110), 
    'size':(372, 24), 
    'backgroundColor':(246, 246, 127), 
    'editable':False, 
    'font':{'faceName': u'DejaVu Sans Mono', 'size': 11}, 
    },

{'type':'TextField', 
    'name':'proxim', 
    'position':(210, 135), 
    'size':(75, 24), 
    'alignment':'right', 
    'backgroundColor':(211, 255, 211), 
    'editable':False, 
    'font':{'faceName': u'Monospace', 'size': 11}, 
    'foregroundColor':(255, 255, 255), 
    },

{'type':'TextField', 
    'name':'bearing', 
    'position':(363, 135), 
    'size':(50, 24), 
    'alignment':'right', 
    'backgroundColor':(211, 255, 211), 
    'editable':False, 
    'font':{'faceName': u'Monospace', 'size': 11}, 
    'foregroundColor':(255, 255, 255), 
    'text':'Copy', 
    },

{'type':'TextField', 
    'name':'clck', 
    'position':(470, 138), 
    'size':(60, -1), 
    'border':'none', 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'secs_since', 
    'position':(531, 135), 
    'size':(50, 24), 
    'alignment':'right', 
    'editable':False, 
    'font':{'faceName': u'Monospace', 'size': 11}, 
    'foregroundColor':(165, 42, 42), 
    'text':'123', 
    },

{'type':'TextField', 
    'name':'counterField', 
    'position':(390, 399), 
    'size':(70, -1), 
    'border':'none', 
    'editable':False, 
    'text':'0', 
    },

{'type':'TextField', 
    'name':'LOA', 
    'position':(411, 186), 
    'size':(55, 24), 
    'alignment':'right', 
    'backgroundColor':(233, 230, 212), 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'beam', 
    'position':(527, 185), 
    'size':(55, 24), 
    'alignment':'right', 
    'backgroundColor':(233, 230, 212), 
    'editable':False, 
    },

{'type':'TextField', 
    'name':'LAT', 
    'position':(430, 245), 
    'size':(150, 24), 
    'editable':False, 
    'font':{'faceName': u'Monospace', 'size': 11}, 
    'foregroundColor':(165, 42, 42), 
    },

{'type':'TextField', 
    'name':'LON', 
    'position':(430, 270), 
    'size':(150, 24), 
    'editable':False, 
    'font':{'faceName': u'Monospace', 'size': 11}, 
    'foregroundColor':(165, 42, 42), 
    },

{'type':'TextField', 
    'name':'dest', 
    'position':(410, 160), 
    'size':(172, 24), 
    'backgroundColor':(233, 230, 212), 
    'editable':False, 
    },

{'type':'RadioGroup', 
    'name':'sortBy', 
    'position':(10, 384), 
    'size':(138, -1), 
    'backgroundColor':(233, 230, 212), 
    'items':['proxim', 'clck'], 
    'label':'sort by:', 
    'layout':'horizontal', 
    'max':1, 
    'stringSelection':'proxim', 
    },

{'type':'TextField', 
    'name':'selectedFld', 
    'position':(510, 396), 
    'size':(33, 22), 
    'alignment':'center', 
    'editable':False, 
    'text':'0', 
    },

{'type':'Button', 
    'name':'nextButt', 
    'position':(552, 396), 
    'size':(28, 23), 
    'font':{'size': 10}, 
    'label':'>', 
    },

{'type':'Button', 
    'name':'prevButt', 
    'position':(471, 396), 
    'size':(29, 23), 
    'font':{'size': 10}, 
    'label':'<', 
    },

{'type':'List', 
    'name':'rangeList', 
    'position':(10, 60), 
    'size':(138, 315), 
    'items':[], 
    },

] # end components
} # end background
] # end backgrounds
} }
